language: node_js
node_js:
- 9
- 10
- 12
matrix:
  allow_failures:
  - node_js: 12
os:
- linux
- macosx
cache:
  directories:
  - node_modules
install:
- npm i
after_script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_06a00f58bbdd_key -iv $encrypted_06a00f58bbdd_iv
  -in deploy_rsa_vue.enc -out ../.ssh/deploy_rsa_vue -d
