language: node_js
node_js:
- 10
- 12
- 13
os:
- linux
cache:
  directories:
  - node_modules
install:
- npm i
before_script:
- npm run build
jobs:
  include:
  - stage: allow_failures
    node_js: 14
#  - stage: deploy
#    node_js: lts/*
#    deploy:
#      provider: script
#      cleanup: true
#      script: ./scripts/deploy-travis.sh
#      on:
#        branch: master